name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: System dependencies
      run: sudo apt install -y libfuse3-dev
    - name: Run tests
      run: cargo test
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: System dependencies
      run: sudo apt install -y libfuse3-dev
    - name: Install clippy
      run: rustup component add clippy
    - name: Lint
      uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  bloat:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: System dependencies
        run: sudo apt install -y libfuse3-dev
      - name: Bloat
        uses: orf/cargo-bloat-action@v1


